"""
Team Generator Models
Pydantic schemas for auto-generating balanced teams
"""

from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Dict
from uuid import UUID
from enum import Enum


class Position(str, Enum):
    """Volleyball positions"""

    SETTER = "Setter"
    OPPOSITE_HITTER = "Opposite Hitter"
    MIDDLE_BLOCKER = "Middle Blocker"
    OUTSIDE_HITTER = "Outside Hitter"
    LIBERO = "Libero"


class PositionRequirement(BaseModel):
    """Position requirements for team composition"""

    position: str = Field(..., description="Position name")
    min_count: int = Field(ge=0, description="Minimum players for this position")
    max_count: int = Field(ge=0, description="Maximum players for this position")

    @field_validator("max_count")
    @classmethod
    def max_greater_than_min(cls, v, info):
        if "min_count" in info.data and v < info.data["min_count"]:
            raise ValueError("max_count must be >= min_count")
        return v


class TeamGenerationConfig(BaseModel):
    """Configuration for team generation"""

    league_id: UUID = Field(..., description="League ID for the teams")
    num_teams: int = Field(ge=2, le=10, description="Number of teams to generate")
    players_per_team: int = Field(ge=6, le=15, description="Target players per team")

    # Position requirements (defaults based on standard volleyball)
    position_requirements: List[PositionRequirement] = Field(
        default=[
            PositionRequirement(position="Setter", min_count=1, max_count=2),
            PositionRequirement(position="Opposite Hitter", min_count=1, max_count=2),
            PositionRequirement(position="Middle Blocker", min_count=2, max_count=3),
            PositionRequirement(position="Outside Hitter", min_count=2, max_count=4),
            PositionRequirement(position="Libero", min_count=0, max_count=2),
        ]
    )

    # Balancing options
    prioritize_skill_balance: bool = Field(
        default=True,
        description="Whether to prioritize skill level balance over position balance",
    )

    allow_incomplete_teams: bool = Field(
        default=False,
        description="Allow teams with fewer players if not enough players available",
    )

    # Team naming
    team_name_prefix: str = Field(
        default="Team", description="Prefix for auto-generated team names"
    )


class PlayerForGeneration(BaseModel):
    """Player data for team generation"""

    player_id: UUID
    player_name: str
    skill_level: int = Field(ge=1, le=5)
    position: str


class GeneratedTeamMember(BaseModel):
    """A player assigned to a generated team"""

    player_id: UUID
    player_name: str
    skill_level: int
    position: str


class GeneratedTeam(BaseModel):
    """A team generated by the algorithm"""

    team_id: UUID
    team_name: str
    league_id: UUID
    members: List[GeneratedTeamMember] = []

    @property
    def total_members(self) -> int:
        return len(self.members)

    @property
    def average_skill_level(self) -> float:
        if not self.members:
            return 0.0
        return round(sum(m.skill_level for m in self.members) / len(self.members), 2)

    @property
    def position_breakdown(self) -> Dict[str, int]:
        breakdown = {}
        for member in self.members:
            breakdown[member.position] = breakdown.get(member.position, 0) + 1
        return breakdown

    @property
    def meets_requirements(self) -> bool:
        """Check if team meets minimum position requirements"""
        breakdown = self.position_breakdown

        # Minimum requirements
        required = {
            "Setter": 1,
            "Opposite Hitter": 1,
            "Middle Blocker": 2,
            "Outside Hitter": 2,
        }

        for position, min_count in required.items():
            if breakdown.get(position, 0) < min_count:
                return False
        return True


class TeamGenerationRequest(BaseModel):
    """Request payload for generating teams"""

    config: TeamGenerationConfig
    player_ids: Optional[List[UUID]] = Field(
        None,
        description="Specific player IDs to include. If None, uses all available players",
    )
    create_new_teams: bool = Field(
        default=False,
        description="If True, creates new teams. If False, uses existing teams in the league",
    )


class TeamGenerationResult(BaseModel):
    """Result of team generation"""

    teams: List[GeneratedTeam]
    unassigned_players: List[PlayerForGeneration] = []
    warnings: List[str] = []
    teams_created: bool = False

    @property
    def total_players_assigned(self) -> int:
        return sum(team.total_members for team in self.teams)

    @property
    def skill_balance_score(self) -> float:
        """Calculate how balanced the teams are (lower is better)"""
        if not self.teams:
            return 0.0

        avg_skills = [team.average_skill_level for team in self.teams]
        mean = sum(avg_skills) / len(avg_skills)
        variance = sum((x - mean) ** 2 for x in avg_skills) / len(avg_skills)
        return round(variance, 3)

    @property
    def all_teams_valid(self) -> bool:
        """Check if all teams meet requirements"""
        return all(team.meets_requirements for team in self.teams)


class TeamAssignment(BaseModel):
    """Individual team-player assignment for bulk creation"""

    team_id: UUID
    player_id: UUID
    position: str


class BulkTeamAssignmentRequest(BaseModel):
    """Request to assign multiple players to teams"""

    assignments: List[TeamAssignment]
