"""generate initial migration

Revision ID: 0eac67be5f8e
Revises: 
Create Date: 2025-11-28 05:11:56.149193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eac67be5f8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('cognito_sub', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_cognito_sub'), 'admin', ['cognito_sub'], unique=True)
    op.create_table('league',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('default_position', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('skill_level',
    sa.Column('skill_level_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('skill_level_id')
    )
    op.create_table('player_skill',
    sa.Column('player_skill_id', sa.UUID(), nullable=False),
    sa.Column('date_assigned', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('skill_level_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_by'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['skill_level_id'], ['skill_level.skill_level_id'], ),
    sa.PrimaryKeyConstraint('player_skill_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('match',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('team1_id', sa.UUID(), nullable=False),
    sa.Column('team2_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['team1_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('team_player',
    sa.Column('team_player_id', sa.UUID(), nullable=False),
    sa.Column('join_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('leave_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('team_player_id')
    )
    op.create_table('match_team_stats',
    sa.Column('match_team_stats_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('sets_won', sa.Integer(), nullable=True),
    sa.Column('sets_lost', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.match_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('match_team_stats_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_team_stats')
    op.drop_table('team_player')
    op.drop_table('match')
    op.drop_table('team')
    op.drop_table('player_skill')
    op.drop_table('skill_level')
    op.drop_table('player')
    op.drop_table('league')
    op.drop_index(op.f('ix_admin_cognito_sub'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
