"""2nd migration: removed admin table

Revision ID: 14f089d20272
Revises: 0eac67be5f8e
Create Date: 2025-12-02 02:05:04.149781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14f089d20272"
down_revision: Union[str, None] = "0eac67be5f8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Drop FK constraint first
    op.drop_constraint(
        op.f("player_skill_evaluated_by_fkey"), "player_skill", type_="foreignkey"
    )

    # 2. Drop the referencing column
    op.drop_column("player_skill", "evaluated_by")

    # 3. Drop indexes referencing the admin table
    op.drop_index(op.f("ix_admin_cognito_sub"), table_name="admin")

    # 4. Drop the admin table
    op.drop_table("admin")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_skill",
        sa.Column("evaluated_by", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("player_skill_evaluated_by_fkey"),
        "player_skill",
        "admin",
        ["evaluated_by"],
        ["admin_id"],
    )
    op.create_table(
        "admin",
        sa.Column("admin_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("cognito_sub", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("admin_id", name=op.f("admin_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("admin_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "username",
            name=op.f("admin_username_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_admin_cognito_sub"), "admin", ["cognito_sub"], unique=True)
    # ### end Alembic commands ###
