"""Add skill level to player model instead of creating a separate module

Revision ID: 19fb899eac1e
Revises: b6830ad8ac3f
Create Date: 2025-12-09 02:29:48.989040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19fb899eac1e"
down_revision: Union[str, None] = "b6830ad8ac3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_level")
    op.drop_table("player_skill")
    op.add_column("player", sa.Column("skill_level", sa.Integer(), nullable=True))
    op.add_column("player", sa.Column("skill_notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "skill_notes")
    op.drop_column("player", "skill_level")
    op.create_table(
        "player_skill",
        sa.Column("player_skill_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "date_assigned",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("player_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("skill_level_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.player_id"],
            name=op.f("player_skill_player_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_level_id"],
            ["skill_level.skill_level_id"],
            name=op.f("player_skill_skill_level_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("player_skill_id", name=op.f("player_skill_pkey")),
    )
    op.create_table(
        "skill_level",
        sa.Column("skill_level_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "level_description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("skill_level_id", name=op.f("skill_level_pkey")),
    )
    # ### end Alembic commands ###
