"""Add cascade delete to league relationships

Revision ID: 2acece205083
Revises: b7e3a0082708
Create Date: 2025-12-08 21:05:10.838717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acece205083'
down_revision: Union[str, None] = 'b7e3a0082708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('match_team2_id_fkey'), 'match', type_='foreignkey')
    op.drop_constraint(op.f('match_league_id_fkey'), 'match', type_='foreignkey')
    op.drop_constraint(op.f('match_team1_id_fkey'), 'match', type_='foreignkey')
    op.create_foreign_key(None, 'match', 'team', ['team2_id'], ['team_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'match', 'league', ['league_id'], ['league_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'match', 'team', ['team1_id'], ['team_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('team_league_id_fkey'), 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'league', ['league_id'], ['league_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key(op.f('team_league_id_fkey'), 'team', 'league', ['league_id'], ['league_id'])
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.create_foreign_key(op.f('match_team1_id_fkey'), 'match', 'team', ['team1_id'], ['team_id'])
    op.create_foreign_key(op.f('match_league_id_fkey'), 'match', 'league', ['league_id'], ['league_id'])
    op.create_foreign_key(op.f('match_team2_id_fkey'), 'match', 'team', ['team2_id'], ['team_id'])
    op.alter_column('match', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
