"""Add skill level to player model v2

Revision ID: 5935d9c175a8
Revises: 19fb899eac1e
Create Date: 2025-12-09 02:35:18.154465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5935d9c175a8"
down_revision: Union[str, None] = "19fb899eac1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("skill_level", sa.Integer(), nullable=True))
    op.add_column("player", sa.Column("skill_notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "skill_notes")
    op.drop_column("player", "skill_level")
    # ### end Alembic commands ###
