"""Replace skill_notes with notes

Revision ID: 72f35915fb5f
Revises: 5935d9c175a8
Create Date: 2025-12-09 02:57:20.538975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72f35915fb5f"
down_revision: Union[str, None] = "5935d9c175a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("notes", sa.String(), nullable=True))
    op.drop_column("player", "skill_notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column("skill_notes", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("player", "notes")
    # ### end Alembic commands ###
