"""Add number of sets to matches

Revision ID: b6830ad8ac3f
Revises: 2acece205083
Create Date: 2025-12-08 21:48:43.255639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6830ad8ac3f"
down_revision: Union[str, None] = "2acece205083"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column(
            "num_of_sets", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "num_of_sets")
    # ### end Alembic commands ###
