"""add cascade delete to match_team_stats foreign keys

Revision ID: bbde523a8799
Revises: 6011d4f7745b
Create Date: 2025-12-09 16:58:58.364874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbde523a8799"
down_revision: Union[str, None] = "6011d4f7745b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("match_team_stats_match_id_fkey"), "match_team_stats", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("match_team_stats_team_id_fkey"), "match_team_stats", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "match_team_stats",
        "match",
        ["match_id"],
        ["match_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "match_team_stats", "team", ["team_id"], ["team_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match_team_stats", type_="foreignkey")
    op.drop_constraint(None, "match_team_stats", type_="foreignkey")
    op.create_foreign_key(
        op.f("match_team_stats_team_id_fkey"),
        "match_team_stats",
        "team",
        ["team_id"],
        ["team_id"],
    )
    op.create_foreign_key(
        op.f("match_team_stats_match_id_fkey"),
        "match_team_stats",
        "match",
        ["match_id"],
        ["match_id"],
    )
    # ### end Alembic commands ###
