"""add cascade delete to player_id and team_player

Revision ID: d40458c2af09
Revises: bbde523a8799
Create Date: 2025-12-10 18:46:56.326428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d40458c2af09"
down_revision: Union[str, None] = "bbde523a8799"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("team_player_player_id_fkey"), "team_player", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "team_player", "player", ["player_id"], ["player_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_player", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_player_player_id_fkey"),
        "team_player",
        "player",
        ["player_id"],
        ["player_id"],
    )
    # ### end Alembic commands ###
