"""Add on delete cascade to team_player relationship

Revision ID: fbf036673d1e
Revises: 72f35915fb5f
Create Date: 2025-12-09 16:45:27.560326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbf036673d1e"
down_revision: Union[str, None] = "72f35915fb5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("team_player_team_id_fkey"), "team_player", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "team_player", "team", ["team_id"], ["team_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_player", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_player_team_id_fkey"),
        "team_player",
        "team",
        ["team_id"],
        ["team_id"],
    )
    # ### end Alembic commands ###
